line-length = 100

[lint]
exclude = ["*.ipynb", "*__init__.py", "custom_model/*"]
select = [
    "D",
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

