line-length = 100

[lint]
exclude = ["*.ipynb", "*__init__.py", "*checkpoint*", "warhammer*", "data/*", "*zero_to_fp32*"]
select = [
    "D",
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

